//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/WCFEXAMPLE")]
    public partial class Person : object
    {
        
        private string ArtField;
        
        private int IDField;
        
        private string NavnField;
        
        private string StedField;
        
        private int UgeField;
        
        private double VaegtField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Art
        {
            get
            {
                return this.ArtField;
            }
            set
            {
                this.ArtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Navn
        {
            get
            {
                return this.NavnField;
            }
            set
            {
                this.NavnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sted
        {
            get
            {
                return this.StedField;
            }
            set
            {
                this.StedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Uge
        {
            get
            {
                return this.UgeField;
            }
            set
            {
                this.UgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Vaegt
        {
            get
            {
                return this.VaegtField;
            }
            set
            {
                this.VaegtField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFishes", ReplyAction="http://tempuri.org/IService1/GetAllFishesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Person>> GetAllFishesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFishById", ReplyAction="http://tempuri.org/IService1/GetFishByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Person> GetFishByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddFish", ReplyAction="http://tempuri.org/IService1/AddFishResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Person> AddFishAsync(ServiceReference1.Person catch1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFish", ReplyAction="http://tempuri.org/IService1/DeleteFishResponse")]
        System.Threading.Tasks.Task DeleteFishAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateFish", ReplyAction="http://tempuri.org/IService1/UpdateFishResponse")]
        System.Threading.Tasks.Task UpdateFishAsync(ServiceReference1.Person c, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFishesByName", ReplyAction="http://tempuri.org/IService1/GetFishesByNameResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Person>> GetFishesByNameAsync(string nameFragment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Person>> GetAllFishesAsync()
        {
            return base.Channel.GetAllFishesAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Person> GetFishByIdAsync(int id)
        {
            return base.Channel.GetFishByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Person> AddFishAsync(ServiceReference1.Person catch1)
        {
            return base.Channel.AddFishAsync(catch1);
        }
        
        public System.Threading.Tasks.Task DeleteFishAsync(int id)
        {
            return base.Channel.DeleteFishAsync(id);
        }
        
        public System.Threading.Tasks.Task UpdateFishAsync(ServiceReference1.Person c, int id)
        {
            return base.Channel.UpdateFishAsync(c, id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.Person>> GetFishesByNameAsync(string nameFragment)
        {
            return base.Channel.GetFishesByNameAsync(nameFragment);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:48662/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
